- name: Run Crond tasks 
  import_tasks: redhat.yml
  when: (ansible_facts['os_family']|lower == 'redhat') or (ansible_facts['os_family']|lower == 'centos')
- import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
