- name: set all k8s nodes
  hosts: notebook
  user: root
  gather_facts: yes
  tasks:
    - include_role:
        name: vpn-nebula
      vars:
        nebula_action: add_node
        lighthouse_ip: 192.168.168.1
        lighthouse_endpoint: onwalk.net:4242
        node_name: notebook
