- name: set all k8s nodes
  hosts: localhost
  user: root
  gather_facts: no
  tasks:
    - include_role:
        name: vpn-nebula
      vars:
        nebula_action: sign_node
        node_name: notebook
        node_ipv4: "192.168.168.4/24"
