- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command facted
  set_fact: 
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: get certificate key raw
  shell: kubeadm init phase upload-certs --experimental-upload-certs
  register: certificate_key_raw

- name: set certificate key facted
  set_fact:
    cert_key: "{{ certificate_key_raw.stdout_lines[-1] }}"

- name: Show Debug Info
  debug: var={{ hostvars[groups[master_group][0]] }}  verbosity=0
