- name: join master nodes
  shell: "{{ hostvars[groups[master_group][0]].join_command }} --experimental-control-plane --certificate-key {{ hostvars[groups[master_group][0]].cert_key }}"
  when: ( inventory_hostname in groups[master_group] ) and ( inventory_hostname not in groups[master_group][0] )

- name: Set kubectl config
  import_tasks: set_kubectl_config.yml
  when: ( inventory_hostname in groups[master_group] ) and ( inventory_hostname not in groups[master_group][0] )

