{% for item in storage.keys() %}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ storage[item]pv_name }}
spec:
  capacity:
    storage: {{ storage[item]pv_size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nolock
    - nfsvers=3
  nfs:
    path: {{ cluster.nfs_path }}/{{ storage[item]pv_sub_path }}
    server: {{ cluster.nfs_server }}
---
{% endfor %}
