- name: sync certs for masters
  hosts: "{{ hostgroup }}"
  user: root
  gather_facts: no
  tasks:
  - name: sync all certs
    copy: src={{ item }} dest={{ item }}
    with_items:
      - /etc/kubernetes/pki/
