apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v{{ version }}
imageRepository: {{ image_repo }}
controlPlaneEndpoint: "{{ api_vip }}:6443"
networking:
  dnsDomain: {{ domain }}
  serviceSubnet: {{ service_subnet }}
  podSubnet: {{ pod_subnet }}
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
  - 127.0.0.1
  - localhost
{% for item in groups['master'] %}
  - {{ item }}
  - {{ hostvars[item].ansible_default_ipv4.address }}
{% endfor %}
