- name: set ssh pub key
  hosts: "{{ hostgroup }}"
  user: root
  gather_facts: no
  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
