apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ pv_name }}
spec:
  capacity:
    storage: {{ pv_size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nolock
    - nfsvers=3
  nfs:
    path: {{ nas_path }}
    server: {{ nas_ip }}


