{%- set k8s_cha = cha_ip -%}
{%- set pkg_ip  = pkg_ip -%}
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
kubernetesVersion: v1.14.2
imageRepository: "{{ pkg_ip }}:5000"
networkPlugin: cni
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  podSubnet: "10.244.0.0/16"
  serviceSubnet: 10.96.0.0/12
