- name: Add docker Repo
  command: "yum-config-manager --add-repo {{ repo }}"
- name: update Repo Cache
  command: "yum makecache"
- name: Clean Old Packages
  command: "yum remove docker-ce-cli docker-ce -y"
- name: Install Packages
  command: "yum install {{ item }} -y"
  with_items:
    - docker-ce-cli-{{ version }}
    - docker-ce-{{ version }}
  notify:
    - Restart docker service
    - Enable docker service

- name: Ensure Dockerd is Running
  shell: "systemctl restart docker && systemctl enable docker"

- name: waiting for dockerd ready
  shell: "systemctl status docker"
  register: docker_stats
  until:
    - 'docker_stats.rc == 0'
  retries: 6
  delay: 10
- name: Show Debug Info
  debug: var=docker_stats verbosity=0
