- name: Install Docker Packages  
  import_tasks: install_docker.yml
  when: inventory_hostname in groups[host_group]
- name: Set Docker Config 
  import_tasks: set_docker.yml
  when: inventory_hostname in groups[host_group]
