- name: init master cluster
  hosts: "{{ hostgroup }}"
  user: root
  gather_facts: no
  tasks:
  - name: run kubeadm init script 
    shell: "systemctl restart kubelet && kubeadm init --config /var/spool/kubeadm-init.yaml"
    async: 120
    poll: 5
